import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";

// Montserrat font with weights 400 (Regular) and 700 (Bold)
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "E-Learning Platform | Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
